[[plugins]]
repo = 'Shougo/vimproc'
  [[plugins.build]]
  windows = 'tools\\update-dll-mingw'
  cygwin  = 'make -f make_cygwin.mak'
  mac     = 'make -f make_mac.mak'
  linux   = 'make'
  unix    = 'gmake'

# プラグインの為のライブラリ
[[plugins]]
repo = 'mattn/webapi-vim'    # HTTPライブラリ
[[plugins]]
repo = 'tpope/vim-repeat'    # プラグイン機能の繰り返し

# 補完
[[plugins]]
repo = 'cohama/lexima.vim'   # 対応する括弧やクオートを補完
[[plugins]]
repo = 'kana/vim-smartchr'   # 入力からの補完
[[plugins]]
repo = 'tyru/caw.vim'        # コメントアウト

# 移動
[[plugins]]
repo = 'Lokaltog/vim-easymotion' # EasyMotion

# テキストオブジェクト
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-fold'
[[plugins]]
repo = 'kana/vim-textobj-indent'
[[plugins]]
repo = 'kana/vim-textobj-lastpat'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'osyo-manga/vim-textobj-from_regexp'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'rhysd/vim-textobj-anyblock'

# オペレータ
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

# 整形
[[plugins]]
repo = 'Align'                         # 特定文字ベースの文書整形
[[plugins]]
repo = 'PreserveNoEOL'                 # EOL設定

# カラーリング
[[plugins]]
repo = 'morhetz/gruvbox'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides' # インデント

# ステータスライン
[[plugins]]
repo = 'bling/vim-airline'

# Git
[[plugins]]
repo = 'tpope/vim-git'
[[plugins]]
repo = 'tpope/vim-fugitive'  # Git

# コードチェック
[[plugins]]
repo = 'scrooloose/syntastic'

# 外部ツール起動
[[plugins]]
repo = 'edkolev/tmuxline.vim'
