# Darkness wares
[[plugins]]
repo = 'Shougo/dein.vim'
[[plugins]]
repo = 'Shougo/denite.nvim'
# [[plugins]]
# repo = 'Shougo/neoyank.vim'
# depends = ['denite.vim']
[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['denite.vim']
[[plugins]]
repo = 'Shougo/deoplete.nvim'
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

# Completion in insert mode
[[plugins]]
repo = 'cohama/lexima.vim'
[[plugins]]
repo = 'kana/vim-smartchr'
[[plugins]]
repo = 'tyru/caw.vim'

# Jumping cursor
[[plugins]]
repo = 'Lokaltog/vim-easymotion'
[[plugins]]
repo = 'christoomey/vim-tmux-navigator'

# Text object
[[plugins]]
repo = 'kana/vim-textobj-user'
[[plugins]]
repo = 'kana/vim-textobj-fold'
[[plugins]]
repo = 'kana/vim-textobj-indent'
[[plugins]]
repo = 'kana/vim-textobj-lastpat'
[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
[[plugins]]
repo = 'osyo-manga/vim-textobj-from_regexp'
[[plugins]]
repo = 'thinca/vim-textobj-between'
[[plugins]]
repo = 'rhysd/vim-textobj-anyblock'
[[plugins]]
repo = 'lucapette/vim-textobj-underscore'
[[plugins]]
repo = 'tpope/vim-abolish'

# Operator
[[plugins]]
repo = 'kana/vim-operator-user'
[[plugins]]
repo = 'rhysd/vim-operator-surround'

# Alignment
[[plugins]]
repo = 'Align'
[[plugins]]
repo = 'Chiel92/vim-autoformat'
[[plugins]]
repo = 'PreserveNoEOL'

# Coloring
[[plugins]]
repo = 'morhetz/gruvbox'
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

# Status line
[[plugins]]
repo = 'itchyny/lightline.vim'
[[plugins]]
repo = 'shinchu/lightline-gruvbox.vim'

# Window
[[plugins]]
repo = 'kana/vim-submode'

# Git
[[plugins]]
repo = 'tpope/vim-git'
[[plugins]]
repo = 'tpope/vim-fugitive'

# Syntax checker
[[plugins]]
repo = 'scrooloose/syntastic'

# Status line exporter
# [[plugins]]
# repo = 'edkolev/tmuxline.vim'

# File manager
[[plugins]]
repo = 'minodisk/nvim-finder'
build = 'make'
