# # neocomplete
# [[plugins]]
# repo = 'Shougo/neocomplete.vim'
# on_i = 1
# [[plugins]]
# repo = 'Shougo/neosnippet'
# on_source = ['neocomplete.vim']
# [[plugins]]
# repo = 'Shougo/neosnippet-snippets'
# on_source = ['neocomplete.vim']

# TypeScript
# [[plugins]]
# repo = 'jason0x43/vim-js-indent'
# on_ft = ['typescript']
# [[plugins]]
# repo = 'Chiel92/vim-autoformat'
# on_ft = ['typescript']

# deoplete
[[plugins]]
repo = 'mhartington/deoplete-typescript'
on_ft = ['typescript']
# [[plugins]]
# repo = 'zchee/deoplete-go'
# on_ft = ['go']
# build = 'make'

# TypeScript
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
on_source = ['vimproc.vim']
# Flow
[[plugins]]
repo = 'flowtype/vim-flow'
on_ft = ['javascript']

# シンタックスハイライト
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'         # ログファイル
on_ft = ['log']
[[plugins]]
repo = 'keith/tmux.vim'                  # tmux
on_ft = ['tmux']
[[plugins]]
repo = 'nginx.vim'
on_ft = ['nginx']
[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = ['ruby']
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']
[[plugins]]
repo = 'othree/html5.vim'                # HTML5
on_ft = ['html']
[[plugins]]
repo = 'leafgarland/typescript-vim'      # TypeScript
on_ft = ['typescript']
[[plugins]]
repo = 'othree/yajs.vim'                 # JavaScript ES6
on_ft = ['javascript']
[[plugins]]
repo = 'digitaltoad/vim-pug'
on_ft = ['pug']
[[plugins]]
repo = 'slim-template/vim-slim'          # Slim
on_ft = ['slim']
[[plugins]]
repo = 'cakebaker/scss-syntax.vim'       # Sass
on_ft = ['sass']
[[plugins]]
repo = 'wavded/vim-stylus'               # Stylus
on_ft = ['stylus']
[[plugins]]
repo = 'groenewege/vim-less'
on_ft = ['less']
[[plugins]]
repo = 'kchmck/vim-coffee-script'        # CoffeeScript
on_ft = ['coffee']
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'         # Dockerfile
on_ft = ['dockerfile']
[[plugins]]
repo = 'markcornick/vim-terraform'       # Terraform
on_ft = ['terraform']
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go', 'gohtmltmpl', 'gotexttmpl']
