# Completion
[[plugins]]
repo = 'mhartington/deoplete-typescript'
on_ft = ['typescript']
# [[plugins]]
# repo = 'zchee/deoplete-go'
# on_ft = ['go']
# build = 'make'

# Language tool
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go', 'gohtmltmpl', 'gotexttmpl']
[[plugins]]
repo = 'Quramy/tsuquyomi'
on_ft = ['typescript']
on_source = ['vimproc.vim']
[[plugins]]
repo = 'flowtype/vim-flow'
on_ft = ['javascript']

# Syntax highlighter
[[plugins]]
repo = 'tpope/vim-markdown'
on_ft = ['markdown']
[[plugins]]
repo = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']
[[plugins]]
repo = 'markcornick/vim-terraform'
on_ft = ['terraform']
[[plugins]]
repo = 'nginx.vim'
on_ft = ['nginx']
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']
[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'
on_ft = ['log']
[[plugins]]
repo = 'keith/tmux.vim'
on_ft = ['tmux']
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']
[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript']
[[plugins]]
repo = 'othree/html5.vim'
on_ft = ['html']
# [[plugins]]
# repo = 'digitaltoad/vim-pug'
# on_ft = ['pug']
# [[plugins]]
# repo = 'slim-template/vim-slim'
# on_ft = ['slim']
# [[plugins]]
# repo = 'cakebaker/scss-syntax.vim'
# on_ft = ['sass']
# [[plugins]]
# repo = 'wavded/vim-stylus'
# on_ft = ['stylus']
# [[plugins]]
# repo = 'groenewege/vim-less'
# on_ft = ['less']
# [[plugins]]
# repo = 'kchmck/vim-coffee-script'
# on_ft = ['coffee']
# [[plugins]]
# repo = 'vim-ruby/vim-ruby'
# on_ft = ['ruby']
# [[plugins]]
# repo = 'tpope/vim-rails'
# on_ft = ['ruby']
